#pragma once
#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>
#include <SFML/System.hpp>
#include <iostream>
#include <stdexcept>
#include <vector>
#include "Coordinates.h"
#include "Exceptions.h"
